---
- name: stop wireguard service
  service:
    name: wg-quick@{{ wg_service }}
    state: stopped
  listen: "reload wireguard"

- name: copy config file
  template:
    src: files/{{ wg_conffile }}
    dest: /etc/wireguard/{{ wg_conffile }}
    mode: 0600
    owner: root
    group: root
  listen: "reload wireguard"

- name: start wireguard service
  service:
    name: wg-quick@{{ wg_service }}
    state: started
  listen: "reload wireguard"
