---
  - name: check for updates
    yum:
      list: updates
      update_cache: true
    register: check_result

  - name: install updates
    yum:
      name: "*"
      state: latest
    when: check_result['results'] | length > 0

  - name: result
    debug:
      msg: "No updates available"
    when: check_result['results'] | length == 0

  - name: result
    debug:
      msg: There are "{{ check_result['results'] | length }}" updates installed.
    when: check_result['results'] | length > 0
