---
  - name: install yum-utils
    yum:
      name: yum-utils
      state: latest

  - name: check if pending reboot
    shell:
      cmd: if [[ $(needs-restarting -r) == *"No core libraries"* ]]; then echo no; else echo yes; fi
    register: checkreboot
    changed_when: checkreboot.stdout.find("yes") != -1

  - name: reboot server
    reboot:
      reboot_timeout: 1800
      test_command: uptime 
    when: checkreboot['changed'] == true

  - name: check for updates
    yum:
      list: updates
      update_cache: true
    register: check_result

  - name: install updates
    yum:
      name: "*"
      state: latest
    when: check_result['results'] | length > 0
    notify: check reboot

  - name: result
    debug:
      msg: "No updates available"
    when: check_result['results'] | length == 0
