version: "3"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Manila
      - UMASK_SET=022 #optional
    volumes:
      - /docker-data/radarr/config2:/config
      - /nfs-share/movies:/movies
      - /nfs-share/torrent:/downloads
    networks:
      - media-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.rule=Host(`rad.jdut.me`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=le"
      - "traefik.docker.network=media-net"
    restart: unless-stopped

networks:
  media-net:
    external: true
