- name: create directory
  file:
    path: /{{ docker_directory }}/{{ item }}/
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true
  loop:
    - alertmanager

- name: install compose file
  template:
    src: files/docker-compose.yml
    dest: /{{ docker_directory }}/{{ item }}/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart alertmanager
  become: true
  loop:
    - alertmanager

- name: copy config file
  template:
    src: files/config.yml
    dest: /{{ docker_directory }}/alertmanager/
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart alertmanager
  become: true

- name: allow port 9093
  firewalld:
    port: 9093/tcp
    state: enabled
    permanent: true
    immediate: true
  become: true
