- name: create directory
  file:
    path: /{{ docker_directory }}/{{ item.dir }}/
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ item.mode }}"
  become: true
  loop:
    - { dir: 'prometheus', mode: '0755' }
    - { dir: 'prometheus/data', mode: '0777' }
    - { dir: 'prometheus/config', mode: '0755' }

- name: install compose file
  template:
    src: files/docker-compose.yml
    dest: /{{ docker_directory }}/{{ item }}/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart prometheus
  become: true
  loop:
    - prometheus

- name: copy config file
  template:
    src: files/prometheus.yml
    dest: /{{ docker_directory }}/prometheus/config/
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: reload prometheus
  become: true

- name: copy rule files
  copy:
    src: files/{{ item }}
    dest: /{{ docker_directory }}/prometheus/config/{{ item }}
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: reload prometheus
  become: true
  loop:
    - app.rules
    - container.rules
    - host_hardware.rules
    - vm_hardware.rules

- name: copy reload-prometheus
  copy:
    src: files/reload-prometheus
    dest: /usr/local/bin/
    mode: 0755
    owner: sep
    group: sep
  become: true
