version: "2.2"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic-net
    environment:
      ELASTICSEARCH_URL: 'http://192.168.1.73:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
      XPACK_GRAPH_ENABLED: 'false'
      XPACK_ML_ENABLED: 'false'
      XPACK_REPORTING_ENABLED: 'false'
      XPACK_WATCHER_ENABLED: 'false'
    cpus: '1.5'
    restart: unless-stopped

networks:
  elastic-net:
    external: true
