- hosts: node-2
  #tags: node-2
  roles:
    - docker-network
    - jellyfin
    - cadvisor
    - ddclient
    - filebeat
    - traefik
    - nextcloud
    - bitwarden
    - tiddlywiki
    - heimdall
    - healthchecks
    - radarr
    - jackett
    - qbittorrent
    - transmission

- hosts: node-3
  roles:
    - docker-network
    - cadvisor
    - filebeat
    - prometheus
    - grafana
    - alertmanager
    - elasticsearch
    - logstash
    - kibana

- hosts: droplet-1
  #tags: droplet-1
  roles:
    - docker-network
    - blackbox-exporter
    - cadvisor
    - filebeat
    - haproxy

- hosts: vpn
  #tags: vpn
  roles:
    - docker-network
    - cadvisor
    - filebeat

- hosts: dns
  #tags: dns
  roles:
    - docker-network
    - cadvisor
    - filebeat
    - pihole
