---
- hosts: test
  become: yes
  tasks:
    - name: configure iptables
      shell:
        cmd: |
          cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
    - name: apply iptbles config
      shell:
        cmd: sysctl --system
    - name: disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: set selinux to permissive mode
      selinux:
        policy: targeted
        state: permissive
    - name: disable swap
      shell:
        cmd: |
          sed -i '/swap/d' /etc/fstab
          swapoff -a
    - name: configure kubernetes repository
      shell:
        cmd: |
          cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kubelet kubeadm kubectl
          EOF
    - name: install kubelet, kubeadm and kubectl
      yum:
        name: [ kubelet, kubeadm, kubectl ]
        state: present
        disable_excludes: kubernetes
    - name: enable kubelet service
      service:
        name: kubelet
        enabled: yes
