---
- name: NFS
  hosts: dns
  become: yes
  tasks:
  - name: install nfs-utils
    yum:
      name: nfs-utils
      state: present

  - name: create nfs directory
    file:
      path: /nfs-share
      state: directory
      owner: "{{ docker_user.name }}"
      group: "{{ docker_user.name }}"

  - name: mount nfs share permanently
    lineinfile:
      path: /etc/fstab
      line: 192.168.1.20:/ /nfs-share nfs defaults 0 0

  - name: mount all
    shell:
      cmd: mount -a
