- name: create directory
  file:
    path: /{{ docker_directory }}/{{ item }}/
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true
  loop:
    - jellyfin

- name: install compose file
  template:
    src: files/docker-compose.yml
    dest: /{{ docker_directory }}/{{ item }}/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart jellyfin
  become: true
  loop:
    - jellyfin
