version: "3"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    container_name: filebeat_{{ ansible_hostname }}
    user: root
    volumes:
      - /{{ docker_directory }}/filebeat/registry:/var/lib/filebeat/registry
      - /{{ docker_directory }}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/host/log:ro
    networks:
      - elastic-net
    restart: unless-stopped

networks:
  elastic-net:
    external: true
