---
- name: start all vms
  proxmox_kvm:
    api_user    : "{{ pve_user }}"
    api_password: "{{ pve_pw }}"
    api_host    : "{{ pve_host }}"
    name        : "{{ item }}"
    node        : "{{ pve_node }}"
    state       : started
  with_items: "{{ groups['nucvms'] }}"
