---
- name: start single vm
  proxmox_kvm:
    api_user    : "{{ pve_user }}"
    api_password: "{{ pve_pw }}"
    api_host    : "{{ pve_host }}"
    name        : "{{ target }}"
    node        : "{{ pve_node }}"
    state       : started
