---
- name: stop all vms
  proxmox_kvm:
    api_user    : "{{ pve_user }}"
    api_password: "{{ pve_pw }}"
    api_host    : "{{ pve_host }}"
    name        : "{{ item }}"
    node        : "{{ pve_node }}"
    state       : stopped
  with_items: "{{ groups['nucvms'] }}"
