#!/usr/bin/env python3
import os

mountpoint = 'nfs-share'
src = '/docker-data/'
dest = '/nfs-share/backup/docker-data_{{ ansible_hostname }}'

check_mountpoint = os.system(f'df -h | grep -i {mountpoint} &> /dev/null')

if check_mountpoint == 0:
    print('Synchronizing files..')
    sync = os.system(f'restic --password-file=/opt/scripts/secret -r {dest} backup {src} --exclude=/docker-data/elasticstack/data')
    print('Done!')

else:
    print(f'{mountpoint} is not found. Performing a remount..')
    remount = os.system('mount -a')
    print('Done!')
    check_mountpoint2 = os.system(f'df -h | grep -i {mountpoint} &> /dev/null')

    if check_mountpoint2 == 0:
        print(f'{mountpoint} is found now. Synchronizing files..')
        sync = os.system(f'restic --password-file=secret -r {dest} backup {src}')
        print('Done!')
    else:
        print(f'Failed to remount {mountpoint}')
