---
#- name: remove vm entry from local host file
#  lineinfile:
#    regexp: "{{ item.value.d_name }}$"
#    path: /etc/hosts
#    state: absent
#  with_dict: "{{ deletevm }}"

- name: remove vm from ansible inventory
  lineinfile:
    regexp: "{{ item.value.d_name }}$"
    path: "{{ project_dir }}/inv.ini"
    state: absent
  with_dict: "{{ deletevm }}"

- name: remove vm name from known_hosts file
  lineinfile:
    regexp: "^{{ item.value.d_name }}"
    path: ~/.ssh/known_hosts
    state: absent
  with_dict: "{{ deletevm }}"

- name: remove vm ip from known_hosts file
  lineinfile:
    regexp: "^{{ item.value.d_ip }}"
    path: ~/.ssh/known_hosts
    state: absent
  with_dict: "{{ deletevm }}"

#- name: remove vm files from host_vars
#  file:
#    path: {{ project_dir }}/host_vars/{{ item.value.d_name }}
#    state: absent
#  with_dict: "{{ deletevm }}"
