---
#clone vm
clonevm:
  vm1:
    c_name: mgr-1
    c_vmid: 3001
    c_ip: 192.168.1.31
    c_cores: 2
    c_cputype: host
    c_cpuunits: 2048 #default is 1024
    c_memory: 2048 #in MB 
    c_env: test
    c_user: sep
    c_group: wheel
    c_userpw: "{{ vm_userpass }}"
    c_userpubkey: "{{ vm_userpubkey }}"
  vm2:
    c_name: wkr-1
    c_vmid: 4001
    c_ip: 192.168.1.41
    c_cores: 2
    c_cputype: host
    c_cpuunits: 2048
    c_memory: 2048
    c_env: test
    c_user: sep
    c_group: wheel
    c_userpw: "{{ vm_userpass }}"
    c_userpubkey: "{{ vm_userpubkey }}"
  vm3:
    c_name: wkr-2
    c_vmid: 4002
    c_ip: 192.168.1.42
    c_cores: 2
    c_cputype: host
    c_cpuunits: 2048
    c_memory: 2048
    c_env: test
    c_user: sep
    c_group: wheel
    c_userpw: "{{ vm_userpass }}"
    c_userpubkey: "{{ vm_userpubkey }}"


#delete vm
deletevm:
  vm1:
    d_name: mgr-1
    d_ip: 192.168.1.31
  vm2:
    d_name: wkr-1
    d_ip: 192.168.1.41
  vm3:
    d_name: wkr-2
    d_ip: 192.168.1.42

