version: "2.2"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash
    environment:
      PIPELINE_WORKERS: '4'
      XPACK_MONITORING_ENABLED: 'false'
    volumes:
      - /docker-data/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    networks:
      - elastic-net
    cpus: '1.5'
    restart: unless-stopped

networks:
  elastic-net:
    external: true
