---
- name: install yum-plugin-copr
  yum:
    name: yum-plugin-copr
    state: latest

- name: enable copr repo
  shell:
    cmd: yum copr enable copart/restic -y

- name: install restic and wget
  yum:
    name: [ restic, wget ]
    state: latest

- name: create backup and scripts directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  with_items:
    - /nfs-share/backup/docker-data_{{ ansible_hostname }}
    - /opt/scripts
  notify: initialize repository

- name: copy restic files
  template:
    src: files/{{ item.file }}
    dest: /opt/scripts
    mode: "{{ item.mod }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  loop:
    - { file: 'docker-data_restic-backup', mod: '0755' }
    - { file: 'secret', mod: '0600' }

- name: create a cron job
  cron:
    name: backup docker files to nfs
    minute: 45
    user: root
    job: /opt/scripts/docker-data_restic-backup && wget http://hea.{{ domain_name }}/ping/{{ hc_id }} && rm -rf {{ hc_id }} 
    cron_file: backup_docker-files
