---
- name: install yum-plugin-copr
  yum:
    name: yum-plugin-copr
    state: latest

- name: enable copr repo
  shell:
    cmd: yum copr enable copart/restic -y
  changed_when: false

- name: install restic and wget
  yum:
    name: [ restic, wget ]
    state: latest

- name: Create scripts directory
  file:
    path: /opt/scripts
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"

- name: copy restic to s3 script
  template:
    src: files/{{ item.file }}
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  loop:
    - { file: 'nextcloud_to_s3.py', dest: '/opt/scripts', mode: '0755' }
    - { file: 'bitwarden_to_s3.py', dest: '/opt/scripts', mode: '0755' }
    - { file: '.restic.env', dest: '/home/sep', mode: '0600' }
    - { file: '.restic-bitwarden.env', dest: '/home/sep', mode: '0600' }
    - { file: 'secret', dest: '/opt/scripts', mode: '0600' }

- name: create cron jobs
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "1"
    user: root
    job: "{{ item.job }}"
    cron_file: "{{ item.file }}"
  loop:
    - { name: 'nextcloud to s3', minute: '30', job: '. /home/{{ docker_user.name }}/.restic.env; /opt/scripts/nextcloud_to_s3.py && wget http://hea.{{ domain_name }}/ping/{{ hc_id3 }} && rm -rf {{ hc_id3 }}', file: 'nextcloud-to-s3' }
    - { name: 'bitwarden to s3', minute: '35', job: '. /home/{{ docker_user.name }}/.restic-bitwarden.env; /opt/scripts/bitwarden_to_s3.py && wget http://hea.{{ domain_name }}/ping/{{ hc_id4 }} && rm -rf {{ hc_id4 }}', file: 'bitwarden-to-s3' }
