global:
  smtp_from: "{{ alertmanager_smtp }}"
  smtp_smarthost: "{{ alertmanager_smtp_smarthost }}"
  smtp_auth_username: "{{ alertmanager_username }}"
  smtp_auth_password: "{{ alertmanager_password }}"
  smtp_auth_identity: "{{ alertmanager_username }}"

route:
  # default route if none match
  receiver: myself
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30m
  group_by: ['alertname', 'job']

receivers:
- name: myself
  email_configs:
  - to: "{{ alertmanager_username }}"
    send_resolved: true
