http:
  routers:
    prometheus-rtr:
      entryPoints:
        - "websecure"
      rule: "Host(`prm.jdut.me`)"
#      middlewares:
#        - pihole-prefix
      service: "prometheus"
      tls:
        certResolver: le
#  middlewares:
#    pihole-prefix:
#      addPrefix:
#        prefix: "/admin"
  services:
    prometheus:
      loadBalancer:
        servers:
        - url: "http://192.168.1.71:9080"
