- name: create directory
  file:
    path: /{{ docker_directory }}/{{ item }}/
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true
  loop:
    - ddclient
    - "ddclient/config"

- name: install compose file
  template:
    src: files/docker-compose.yml
    dest: /{{ docker_directory }}/{{ item }}/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart ddclient
  become: true
  loop:
    - ddclient

- name: copy config file
  template:
    src: files/ddclient.conf
    dest: /{{ docker_directory }}/ddclient/config/ddclient.conf
    mode: 0600
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  become: true
  notify: restart ddclient
