version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:14.3.2.99202101080148-7233-0cbd15890ubuntu18.04.1-ls109
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Manila
      - UMASK=022
      - WEBUI_PORT=8090
    volumes:
      - /{{ docker_directory }}/qbittorrent/config:/config
      - /nfs-share/movies:/downloads
    networks:
      - media-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8090"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbi.{{ domain_name }}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls.certresolver=le"
      - "traefik.docker.network=media-net"
    restart: unless-stopped

networks:
  media-net:
    external: true
