- name: create directory
  file:
    path: /{{ docker_directory }}/{{ item }}/
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true
  loop:
    - elasticsearch

- name: install compose file
  template:
    src: files/docker-compose.yml
    dest: /{{ docker_directory }}/{{ item }}/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart elasticsearch
  become: true
  loop:
    - elasticsearch

- name: create data directory
  file:
    path: /{{ docker_directory }}/{{ item }}/data
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: 0777
  become: true
  loop:
    - elasticsearch

- name: allow port 9200
  firewalld:
    port: 9200/tcp
    state: enabled
    permanent: true
    immediate: true
  become: true
