- name: create directories
  file:
    path: /docker-data/{{ item }}/
    state: directory
    owner: sep
    group: sep
    mode: 0755
  become: true
  loop:
    - traefik
    - "traefik/file-providers"

- name: create files
  file:
    path: /docker-data/traefik/{{ item.name }}
    state: touch
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  become: true
  changed_when: false
  loop:
    - { name: "acme.json", owner: 'root', mode: '0600' }
    - { name: "traefik.log", owner: "{{ docker_user.name }}", mode: '0644' }

- name: install compose
  template:
    src: files/{{ item.file }}
    dest: /docker-data/{{ item.dest }}
    mode: "{{ item.mode }}"
    owner: sep
    group: sep
  notify: restart traefik
  become: true
  loop:
    - { file: 'docker-compose.yml', owner: "{{ docker_user.name }}", mode: '0644', dest: 'traefik' }

- name: copy file providers
  copy:
    src: files/
    dest: /docker-data/traefik/file-providers/
    mode: 0644
    owner: sep
    group: sep
  become: true
