version: "3"
services:
  traefik:
    #image: "traefik:v2.0.0"
    image: "traefik"
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.watch=true
#      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/file-providers
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api=true
      - --certificatesresolvers.le.acme.dnschallenge=true
      - --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare
#      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.le.acme.email=jdut0000@gmail.com
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --serversTransport.insecureSkipVerify=true
      - --log.level=DEBUG
      - --log.filePath=/var/log/traefik.log
    environment:
      - CF_API_EMAIL=jdut0000@gmail.com
      - CF_API_KEY=59b7173ce135f43cedba81582418cde36b58d
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/{{ docker_directory }}/traefik/acme.json:/acme.json"
      - "/{{ docker_directory }}/traefik/traefik.log:/var/log/traefik.log"
      - /{{ docker_directory }}/traefik/file-providers:/file-providers
    networks:
      - proxy-net
      - data-net
      - media-net
      - private-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`tra.jdut.me`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=sep:$$2y$$10$$2kzKPyhbpcOvDvskkwtzvOPn6BIOWeErv0nlo5S4WMFfnEtFkUP86"

      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped

networks:
  proxy-net:
    external: true
  data-net:
    external: true
  media-net:
    external: true
  private-net:
    external: true
