version: "3"
services:
  healthchecks:
    image: linuxserver/healthchecks
    container_name: healthchecks
    environment:
      - PUID=1001
      - PGID=1001
      - SITE_ROOT=http://hea.{{ domain_name }}
      - SITE_NAME=healthchecks
      - DEFAULT_FROM_EMAIL=healthchecks@{{ domain_name }}
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER={{ healthcheck_user }}
      - EMAIL_HOST_PASSWORD={{ healthcheck_pass }}
      - EMAIL_USE_TLS=True
      - ALLOWED_HOSTS=*
      - SUPERUSER_EMAIL={{ healthcheck_user }}
      - SUPERUSER_PASSWORD=[{ healthcheck_pass }}
    volumes:
      - /{{ docker_directory }}/healthchecks/config:/config
    networks:
      - data-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hc.loadbalancer.server.port=8000"
      - "traefik.http.routers.hc.rule=Host(`hea.{{ domain_name }}`)"
      - "traefik.http.routers.hc.entrypoints=websecure"
      - "traefik.http.routers.hc.tls.certresolver=le"
      - "traefik.docker.network=data-net"
    restart: unless-stopped

networks:
  data-net:
    external: true
