version: "3"
services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - "/{{ docker_directory }}/alertmanager:/etc/alertmanager/"
    ports:
      - 9093:9093 
    networks:
      - data-net
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped

networks:
  data-net:
    external: true
