version: "3"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Manila
    volumes:
      - /{{ docker_directory }}/nextcloud/appdata:/config
      - /{{ docker_directory }}/nextcloud/data:/data
    networks:
      - private-net
      - db-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"
      - "traefik.http.routers.nextcloud.rule=Host(`nex.{{ domain_name }}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.docker.network=private-net"
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5
    container_name: mariadb_nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /{{ docker_directory }}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={{ nextcloud_pass }}
      - MYSQL_PASSWORD={{ nextcloud_pass }}
      - MYSQL_DATABASE={{ nextcloud_user }}
      - MYSQL_USER={{ nextcloud_user }}
    networks:
      - db-net
    restart: unless-stopped

networks:
  private-net:
    external: true
  db-net:
    external: true
