global:       
  scrape_interval:     60s
  evaluation_interval: 60s 

  external_labels:
    monitor: 'swarm'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['192.168.1.73:9093']

rule_files:
  - vm_hardware.rules
  - container.rules
  - host_hardware.rules
  - app.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'       
    static_configs:
      - targets:
        - node-3:9100
        - vpn:9100
        - dns:9100
        - nuc-host:9100
        - wg-server:9100
        - node-2:9100

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - node-3:9300
        - dns:9300
        - vpn:9300
        - wg-server:9300
        - node-2:9300

  - job_name: 'healthchecks-docker_data-to-nfs'
    scheme: http
    metrics_path: /projects/fdaff6ef-fd97-4b23-8487-ced3a8b480c5/metrics/{{ hc_api }}
    static_configs:
    - targets: ['hea.{{ domain_name }}']

  - job_name: 'healthchecks-remove-old-docker_data'
    scheme: http
    metrics_path: /projects/9c4a8629-406b-400e-8a65-43928adf244e/metrics/{{ hc_api2 }}
    static_configs:
    - targets: ['hea.{{ domain_name }}']

  - job_name: 'healthchecks-docker_data-to-S3'
    scheme: http
    metrics_path: /projects/c1f4a65b-70ac-484e-939e-ee88550b5e2a/metrics/{{ hc_api3 }}
    static_configs:
    - targets: ['hea.{{ domain_name }}']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        #- http://prm.{{ domain_name }}
        #- http://kib.{{ domain_name }}
        #- http://hea.{{ domain_name }}
        #- http://tra.{{ domain_name }}
        #- http://gra.{{ domain_name }}
        #- http://tid.{{ domain_name }}
        #- http://pih.{{ domain_name }}
        - http://jel.{{ domain_name }}
        #- http://air.{{ domain_name }}
        - http://qbi.{{ domain_name }}
        #- http://jac.{{ domain_name }}
        #- http://rad.{{ domain_name }}
        #- http://por.{{ domain_name }}
        - http://next.{{ domain_name }}
        #- http://piw.{{ domain_name }}
        - http://bitt.{{ domain_name }}
        #- http://trn.{{ domain_name }}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
    #    replacement: node-3:9115  # The blackbox exporter's real hostname:port.
        replacement: 10.10.0.1:9115
