version: "3"
services:
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - /docker-data/ddclient/config:/config
    networks:
      - data-net
    restart: unless-stopped

networks:
  data-net:
    external: true
