version: "3"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Manila
    volumes:
      - /{{ docker_directory }}/heimdall/config:/config
    networks:
      - data-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.heimdall.loadbalancer.server.port=443"
      - "traefik.http.services.heimdall.loadbalancer.server.scheme=https"
      - "traefik.http.routers.heimdall.rule=Host(`hei.jdut.me`)"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls.certresolver=le"
      - "traefik.docker.network=data-net"
    restart: unless-stopped

networks:
  data-net:
    external: true
