version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - /docker-data/prometheus/config/:/etc/prometheus/
      - /docker-data/prometheus/data:/prometheus
    #depends_on:
    #  - cadvisor
    ports:
      - 9080:9090
    networks:
      - data-net
      - db-net
    restart: unless-stopped

networks:
  data-net:
    external: true
  db-net:
    external: true
