- name: create directory
  file:
    path: /{{ docker_directory }}/{{ item }}/
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true
  loop:
    - logstash

- name: install compose file
  template:
    src: files/docker-compose.yml
    dest: /{{ docker_directory }}/{{ item }}/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart logstash
  become: true
  loop:
    - logstash

- name: copy config file
  copy:
    src: files/logstash.conf
    dest: /{{ docker_directory }}/{{ item }}/logstash.conf
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart logstash
  become: true
  loop:
    - logstash

- name: allow port 5044
  firewalld:
    port: 5044/tcp
    state: enabled
    permanent: true
    immediate: true
  become: true
