---
- name: Create nebula directory
  file:
    path: /opt/nebula
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"

- name: Transfer nebula files with variables
  template:
    src: files/{{ item }}
    dest: /opt/nebula
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  loop:
    - ca.crt
    - config.node.yaml
    - "{{ nebula_keyname }}.crt"
    - "{{ nebula_keyname }}.key"

- name: Transfer nebula files
  copy:
    src: files/{{ item.file }}
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  loop:
    - { file: 'nebula', dest: '/opt/nebula', mode: '0755' }
    - { file: 'nebula.service', dest: '/etc/systemd/system/', mode: '0644' }
    - { file: 'start-nebula', dest: '/usr/bin', mode: '0755' }
    - { file: 'stop-nebula', dest: '/usr/bin', mode: '0755' }

- name: start and enable nebula service
  service:
    name: nebula
    state: started
    enabled: yes
